services:
  frontend:
    image: tapnisu/tapni.su:main
    ports:
      - 3000:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--cleanup"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
