import GhRepo from "../components/GhRepo";
import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import useSwr from "swr";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Index: NextPage = () => {
	const args = {
		user: "tapnisu",
		repos: [
			"tapris",
			"website",
			"ytscc",
			"forwarding-discord-telegram",
			"tsukinose",
			"mumei"
		]
	};

	const { data, error } = useSwr<any[]>(
		`/api/ghPinned?user=${args.user}&repos=${args.repos.join("&repos=")}`,
		fetcher
	);

	return (
		<div className="bg-black text-white">
			<Head>
				<title>Alexiy Rybin</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div className="w-full h-screen flex flex-row flex-wrap justify-evenly items-center">
					<span>
						<Image
							src="/avatar.png"
							alt="Avatar"
							width={256}
							height={256}
							className="rounded-full"
						/>
					</span>

					<span>
						<h1 className="text-2xl">
							Hello! I am <span className="text-pink-600">Alexiy Rybin!</span>
							<p className="text-xl text-pink-700">(tapnisu)</p>
						</h1>
					</span>
				</div>

				<div className="grid grid-cols-1 md:grid-cols-2">
					{data?.map((repo: any) => (
						<GhRepo repo={repo} key={repo.id} />
					))}
				</div>
			</main>

			<footer className="flex flex-row flex-wrap justify-between p-8">
				<span className="uppercase">
					<a href="https://github.com/tapnisu">Github</a>/
					<a href="https://t.me/AlexiyRybin">Telegram</a>/
					<a href="https://twitter.com/tapnisu">Twitter</a>
				</span>
				Copyright © 2022 Alexiy Rybin.
			</footer>
		</div>
	);
};

export default Index;
