name: CI

on: push

jobs:
  ubuntu-latest:
    name: Ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint
